apiVersion: apps/v1
kind: Deployment
metadata: # Deployment metadata
  name: user
  namespace: roboshop # Namespace for the deployment
  labels:
    component: user
    project: roboshop
    tier: app
    # This is the deployment for user
spec:
  replicas: 1 # Number of replicas
  selector:
    matchLabels:
      component: user
      project: roboshop
      tier: app
# this is pod definition
  template:
    metadata:
      labels:
        component: user
        project: roboshop
        tier: app
    spec:
      containers:
        - name: user
          image: "{{ .Values.deployment.imageURL}}:{{ .Values.deployment.imageVersion }}"   # User image
          resources:                  # 🔹 Resource configuration
            requests:
              cpu: "50m"              # 🟡 Minimum CPU required
              memory: "128Mi"         # 🟡 Minimum memory required
            limits:
              cpu: "100m"             # 🔴 Max CPU allowed
              memory: "256Mi"         # 🔴 Max memory allowed
          envFrom:
          - configMapRef:
              name: user # Reference to the ConfigMap