apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: roboshop # Namespace for the service
  labels:
    component: user
    project: roboshop
    tier: app
spec:
  selector:
    component: user
    project: roboshop
    tier: app
  ports:
  - protocol: TCP # Protocol for the service
    port: 8080 # user default service port
    targetPort: 8080 # container port