apiVersion: v1
kind: Secret
metadata:
  name: mysql                        # 🔑 Secret name
  labels:
    component: mysql                # 🧩 Logical grouping
    project: roboshop               # 📦 Project name
    tier: database                  # 🗂️ Tier
type: Opaque                        # 🔒 Generic secret
data:
  MYSQL_ROOT_PASSWORD: "Um9ib1Nob3BAMQ=="   # 🔐 base64-encoded root password (Roboshop@1)