apiVersion: v1
kind: Service
metadata:
  name: mysql-headless              # 🌐 Headless service
  namespace: roboshop               # 🧭 Placed in roboshop namespace
  labels:
    component: mysql
    project: roboshop
    tier: database
spec:
  clusterIP: None                   # ❌ No ClusterIP – makes it headless
  selector:
    component: mysql
    project: roboshop
    tier: database
  ports:
  - protocol: TCP
    port: 3306                      # 🚪 Port exposed by service
    targetPort: 3306               # 🎯 Port on container