# 📡 ClusterIP Service for Redis access
apiVersion: v1
kind: Service
metadata:
  name: redis                       # 📡 Standard ClusterIP service
  namespace: roboshop
  labels:
    component: redis
    project: roboshop
    tier: database
spec:
  selector:
    component: redis
    project: roboshop
    tier: database
  ports:
  - protocol: TCP
    port: 6379                      # 🚪 Port exposed to clients
    targetPort: 6379                # 🎯 Container’s internal port