apiVersion: v1
kind: Service
metadata:
  name: cart
  namespace: roboshop # Namespace for the service
  labels:
    component: cart
    project: roboshop
    tier: app
spec:
  selector:
    component: cart
    project: roboshop
    tier: app
  ports:
  - protocol: TCP # Protocol for the service
    port: 8080 # cart default service port
    targetPort: 8080 # container port