# 🔐 Secret for RabbitMQ Credentials
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq                    # 🔑 Secret name
  labels:
    component: rabbitmq            # 🧩 Identifies the component
    project: roboshop              # 📦 Project: roboshop
    tier: database                 # 🗂️ Tier: database
type: Opaque                        # 🔒 Generic key-value secret
data:
  RABBITMQ_DEFAULT_USER: "cm9ib3Nob3A="       # 👤 Username: roboshop (base64)
  RABBITMQ_DEFAULT_PASS: "cm9ib3Nob3AxMjM="   # 🔑 Password: roboshop123 (base64)