# 🏗️ rabbitmq StatefulSet with EBS-based Persistent Volumes
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  namespace: roboshop
  labels:
    component: rabbitmq
    project: roboshop
    tier: database
spec:
  selector:
    matchLabels:
      component: rabbitmq
      project: roboshop
      tier: database               # 🧬 Must match pod template labels
  serviceName: "rabbitmq-headless"    # 🔁 Required for stable network ID
  replicas: 2                      # 🧍🧍 Creates 2 rabbitmq pods
  template:
    metadata:
      labels:
        component: rabbitmq
        project: roboshop
        tier: database
    spec:
      containers:
      - name: rabbitmq
        image: "{{ .Values.statefulset.imageURL}}:{{ .Values.statefulset.imageVersion }}"          # 🐳 rabbitmq official image
        envFrom:
        - secretRef:
            name: rabbitmq          # 🔑 Reference to the secret for credentials
        volumeMounts:
        - name: rabbitmq-data
          mountPath: /var/lib/rabbitmq   # 💾 Mount rabbitmq data directory
  volumeClaimTemplates:
  - metadata:
      name: rabbitmq-data             # 📦 PVC name template
    spec:
      accessModes: [ "ReadWriteOnce" ]  # ✍️ Single node write access
      storageClassName: "roboshop-ebs"  # 📀 EBS-backed storage class
      resources:
        requests:
          storage: 2Gi             # 💽 2Gi per rabbitmq pod